version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=eringiv3
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5431:5432'

  db-test:
    image: postgres:13
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma

volumes:
  postgres:
