version: '3.8'
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=eringiv3
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5431:5432'

volumes:
  postgres:
